"""
CPB v3 — Brique 0 : Auto-découverte, inférence de domaine, génération de taxonomie.

Executed ONCE at startup (not per query). All LLM calls use Llama 3.1 8B via Ollama
(local, zero external API). Fully automatic: no hardcoded categories or taxonomy.
If Llama is unavailable, bootstrap returns an empty result (used_fallback=True).

Steps:
  0a  Discover PII types from ChromaDB metadata (Path A) or Presidio on sample (Path B)
  0b  Infer corpus domain via Llama zero-shot (JSON output)
  0c  Generate domain-specific sensitive categories + Presidio hints via Llama
  0d  Enrich each category with real anonymized phrases + synthetic Llama fallback
  0e  Build L2-normalized SBERT centroids (all-MiniLM-L6-v2, local)
"""

import json
import logging
import os
import re
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import numpy as np
import requests

from config import LLAMA_MODEL, OLLAMA_BASE_URL

logger = logging.getLogger(__name__)


@dataclass
class BootstrapResult:
    domain: str
    domain_confidence: float
    learned_types: set
    dynamic_categories: list
    dynamic_taxonomy: dict        # category -> list[str]
    category_hints: dict          # category -> set[str] (Presidio entity types, generated by Llama)
    centroids: dict               # category -> np.ndarray (384,)
    used_fallback: bool = False


class CPBBootstrapV3:
    """
    Brique 0: one-shot corpus analysis that produces a BootstrapResult.

    Call .run() once in __init__ of the orchestrator. Results are cached
    on the returned dataclass and passed to the v3 components.
    """

    def __init__(
        self,
        store,
        ollama_host: str = OLLAMA_BASE_URL,
        llama_model: str = LLAMA_MODEL,
        seed: int = 42,
    ):
        self.store = store
        self.ollama_host = ollama_host
        self.llama_model = llama_model
        self.seed = seed
        self._embedder = None

    def run(self) -> BootstrapResult:
        """Execute steps 0a → 0e. Returns BootstrapResult. Never raises."""
        try:
            learned_types = self._step_0a()
            chunks_sample = self._sample_chunks(50)
            domain, domain_confidence = self._step_0b(chunks_sample)
            dynamic_categories, category_hints = self._step_0c(domain)
            dynamic_taxonomy = self._step_0d(dynamic_categories, domain, chunks_sample, category_hints)
            centroids = self._step_0e(dynamic_taxonomy)

            result = BootstrapResult(
                domain=domain,
                domain_confidence=domain_confidence,
                learned_types=learned_types,
                dynamic_categories=dynamic_categories,
                dynamic_taxonomy=dynamic_taxonomy,
                category_hints=category_hints,
                centroids=centroids,
                used_fallback=False,
            )
            self._log_mlflow(result)
            logger.info(
                f"[CPBBootstrap] domain={domain} ({domain_confidence:.2f}), "
                f"categories={dynamic_categories}, types={len(learned_types)}"
            )
            return result

        except Exception as exc:
            logger.warning(f"[CPBBootstrap] Failed ({exc!r}), returning empty bootstrap result.")
            return BootstrapResult(
                domain="general",
                domain_confidence=0.0,
                learned_types=set(),
                dynamic_categories=[],
                dynamic_taxonomy={},
                category_hints={},
                centroids={},
                used_fallback=True,
            )

    # ── Step 0a : PII type discovery (Presidio on raw documents) ─────────────

    def _step_0a(self) -> set[str]:
        try:
            from presidio_analyzer import AnalyzerEngine
            analyzer = AnalyzerEngine()
            result = self.store.get(limit=50, include=["documents"])
            docs = result.get("documents") or []
            types: set[str] = set()
            for doc in docs:
                if not doc:
                    continue
                for finding in analyzer.analyze(text=doc[:2000], language="en"):
                    types.add(finding.entity_type.upper())
            logger.info(f"[CPBBootstrap 0a] {len(types)} PII types discovered via Presidio")
            return types
        except Exception as exc:
            logger.warning(f"[CPBBootstrap 0a] Presidio discovery failed: {exc}")
            return set()

    # ── Step 0b : Domain inference ────────────────────────────────────────────

    def _step_0b(self, chunks: list[str]) -> tuple[str, float]:
        excerpt = "\n---\n".join(c[:300] for c in chunks[:10])
        prompt = (
            "You are a corpus analyst. Based on the text excerpts below, "
            "identify the domain of this corpus.\n\n"
            f"Excerpts:\n{excerpt}\n\n"
            "Respond in valid JSON only. "
            'The domain must be exactly one of: medical, financial, legal, general\n'
            'Example: {"domain": "legal", "confidence": 0.9}'
        )
        try:
            raw = self._llama_call(prompt)
            parsed = self._parse_json(raw)
            domain = str(parsed.get("domain", "general")).lower().strip()
            if domain not in {"medical", "financial", "legal", "general"}:
                domain = "general"
            confidence = float(parsed.get("confidence", 0.5))
            return domain, confidence
        except Exception as exc:
            logger.warning(f"[CPBBootstrap 0b] Domain inference failed ({exc}), default=general")
            return "general", 0.0

    # ── Step 0c : Category generation + Presidio hints ───────────────────────

    def _step_0c(self, domain: str) -> tuple[list[str], dict[str, set[str]]]:
        prompt = (
            f"You are a privacy expert. For a corpus in the '{domain}' domain, "
            "list 5 to 8 categories of sensitive personal attributes that must be protected.\n"
            "For each category, also list which Presidio NLP entity types would signal its presence in text.\n"
            "Available Presidio entity types: PERSON, LOCATION, ORGANIZATION, DATE_TIME, NRP, "
            "NATIONALITY, MEDICAL_LICENSE, DISEASE, CHEMICAL, IBAN_CODE, CREDIT_CARD, "
            "US_BANK_NUMBER, EMAIL_ADDRESS, PHONE_NUMBER, US_SSN, US_PASSPORT, IP_ADDRESS\n"
            "Use short uppercase snake_case names for categories.\n"
            "Respond in valid JSON only.\n"
            'Example: {"categories": ['
            '{"name": "HEALTH", "presidio_types": ["MEDICAL_LICENSE", "DISEASE", "CHEMICAL"]}, '
            '{"name": "IMMIGRATION_STATUS", "presidio_types": ["NRP", "NATIONALITY", "LOCATION"]}'
            ']}'
        )
        try:
            raw = self._llama_call(prompt)
            parsed = self._parse_json(raw)
            raw_cats = parsed.get("categories", [])

            categories: list[str] = []
            hints: dict[str, set[str]] = {}
            for item in raw_cats:
                if not isinstance(item, dict):
                    continue
                name = str(item.get("name", "")).upper().strip()
                if not re.match(r"^[A-Z][A-Z0-9_]{1,39}$", name):
                    continue
                categories.append(name)
                types = {str(t).upper().strip() for t in item.get("presidio_types", []) if t}
                if types:
                    hints[name] = types

            if 5 <= len(categories) <= 10:
                logger.info(f"[CPBBootstrap 0c] {len(categories)} categories with {sum(len(v) for v in hints.values())} hints")
                return categories, hints
        except Exception as exc:
            logger.warning(f"[CPBBootstrap 0c] Category generation failed ({exc}), returning empty categories")
        return [], {}

    # ── Step 0d : Anchor phrase enrichment ───────────────────────────────────

    def _step_0d(
        self,
        categories: list[str],
        domain: str,
        chunks: list[str],
        category_hints: dict[str, set[str]],
    ) -> dict[str, list[str]]:
        try:
            from presidio_analyzer import AnalyzerEngine
            from presidio_anonymizer import AnonymizerEngine
            analyzer = AnalyzerEngine()
            anonymizer = AnonymizerEngine()
        except ImportError:
            analyzer = anonymizer = None

        # Split corpus into sentences once
        all_sentences: list[str] = []
        for chunk in chunks:
            for sent in re.split(r"(?<=[.!?])\s+", chunk):
                sent = sent.strip()
                if len(sent) > 20:
                    all_sentences.append(sent)

        taxonomy: dict[str, list[str]] = {}
        for category in categories:
            real = (
                self._collect_real_phrases(category, all_sentences, analyzer, anonymizer, category_hints)
                if analyzer is not None else []
            )
            if len(real) < 3:
                synthetic = self._generate_synthetic_phrases(category, domain)
                real = real + synthetic
            phrases = real[:15] if real else self._fallback_phrases(category)
            taxonomy[category] = phrases

        return taxonomy

    def _collect_real_phrases(
        self,
        category: str,
        sentences: list[str],
        analyzer,
        anonymizer,
        category_hints: dict[str, set[str]],
        max_phrases: int = 15,
    ) -> list[str]:
        relevant_types = category_hints.get(category, None)
        phrases: list[str] = []

        for sent in sentences:
            if len(phrases) >= max_phrases:
                break
            try:
                text = sent[:500]
                results = analyzer.analyze(text=text, language="en")
                if not results:
                    continue
                if relevant_types and not any(r.entity_type in relevant_types for r in results):
                    continue
                anon = anonymizer.anonymize(text=text, analyzer_results=results)
                phrases.append(anon.text)
            except Exception:
                continue

        return phrases

    def _generate_synthetic_phrases(self, category: str, domain: str) -> list[str]:
        label = category.lower().replace("_", " ")
        prompt = (
            f"Generate 3 to 5 short realistic sentences (1-2 sentences each) that describe "
            f"a person's {label} attribute in a {domain or 'legal'} document context. "
            "Do not use real names. "
            "Respond in valid JSON only.\n"
            'Example: {"phrases": ["The individual has a chronic condition.", "She disclosed her faith."]}'
        )
        try:
            raw = self._llama_call(prompt)
            parsed = self._parse_json(raw)
            phrases = [str(p).strip() for p in parsed.get("phrases", []) if len(str(p).strip()) > 15]
            return phrases[:5]
        except Exception:
            return []

    def _fallback_phrases(self, category: str) -> list[str]:
        label = category.lower().replace("_", " ")
        return [
            f"The individual has a sensitive {label} attribute.",
            f"This information concerns {label} and requires protection.",
        ]

    # ── Step 0e : SBERT centroids ─────────────────────────────────────────────

    def _step_0e(self, taxonomy: dict[str, list[str]]) -> dict[str, np.ndarray]:
        return self._build_centroids(taxonomy)

    def _build_centroids(self, taxonomy: dict[str, list[str]]) -> dict[str, np.ndarray]:
        embedder = self._get_embedder()
        centroids: dict[str, np.ndarray] = {}
        for category, sentences in taxonomy.items():
            if not sentences:
                continue
            embs = embedder.embed_texts(sentences)   # (N, 384), L2-normalized
            centroid = embs.mean(axis=0)
            norm = np.linalg.norm(centroid)
            centroids[category] = centroid / (norm + 1e-9)
        return centroids

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _sample_chunks(self, n: int) -> list[str]:
        try:
            result = self.store.get(limit=n, include=["documents"])
            return [d for d in (result.get("documents") or []) if d and d.strip()]
        except Exception:
            return []

    def _llama_call(self, prompt: str) -> str:
        resp = requests.post(
            f"{self.ollama_host}/api/generate",
            json={
                "model": self.llama_model,
                "prompt": prompt,
                "stream": False,
                "format": "json",
                "options": {"temperature": 0, "seed": self.seed},
            },
            timeout=120,
        )
        resp.raise_for_status()
        return resp.json().get("response", "")

    @staticmethod
    def _parse_json(raw: str) -> dict:
        start = raw.find("{")
        end = raw.rfind("}") + 1
        if start == -1 or end == 0:
            raise ValueError("No JSON object in LLM response")
        return json.loads(raw[start:end])

    def _get_embedder(self):
        if self._embedder is None:
            from embeddings.embedder import Embedder
            self._embedder = Embedder()
        return self._embedder

    # ── MLflow traceability ───────────────────────────────────────────────────

    def _log_mlflow(self, result: BootstrapResult) -> None:
        try:
            import mlflow
            mlflow.log_param("cpb_v3_domain", result.domain)
            mlflow.log_param("cpb_v3_domain_confidence", round(result.domain_confidence, 3))
            mlflow.log_param("cpb_v3_categories", ",".join(result.dynamic_categories))
            mlflow.log_param("cpb_v3_learned_types", ",".join(sorted(result.learned_types)))
            mlflow.log_param("cpb_v3_used_fallback", result.used_fallback)
            mlflow.log_param("cpb_v3_seed", self.seed)

            payload = {
                "domain": result.domain,
                "domain_confidence": result.domain_confidence,
                "categories": result.dynamic_categories,
                "category_hints": {k: list(v) for k, v in result.category_hints.items()},
                "taxonomy": {k: v for k, v in result.dynamic_taxonomy.items()},
                "seed": self.seed,
                "used_fallback": result.used_fallback,
            }
            with tempfile.NamedTemporaryFile(
                mode="w", suffix=".json", delete=False, encoding="utf-8"
            ) as f:
                json.dump(payload, f, indent=2, ensure_ascii=False)
                tmp_path = f.name
            mlflow.log_artifact(tmp_path, artifact_path="cpb_v3_bootstrap")
            os.unlink(tmp_path)
        except Exception:
            pass
